import './assets/css/lib/lobipanel/lobipanel.css'
import './assets/css/separate/vendor/lobipanel.min.css'
import './assets/css/lib/jqueryui/jquery-ui.min.css'
import './assets/css/separate/pages/widgets.min.css'
import 'font-awesome/css/font-awesome.css'
import 'bootstrap/dist/css/bootstrap.css'
import './assets/css/main.css'

import './assets/css/lib/bootstrap-sweetalert/sweetalert.css'
import './assets/css/separate/vendor/sweet-alert-animations.min.css'

import './assets/js/lib/popper/popper.min.js'
import './assets/js/lib/tether/tether.min.js'
import 'bootstrap/dist/js/bootstrap.js'
import './assets/js/lib/lobipanel/lobipanel.js'
import './assets/js/plugins.js'
import './assets/js/lib/bootstrap-sweetalert/sweetalert.min'
import './assets/js/lib/jqueryui/jquery-ui.min.js'
import './assets/js/lib/match-height/jquery.matchHeight.js'
import './assets/js/app.js'